// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://xffinwdhcibvoeebfnlz.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InhmZmlud2RoY2lidm9lZWJmbmx6Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3Mzk3MDY0MjIsImV4cCI6MjA1NTI4MjQyMn0.gMem0MZPtowoAjN8xOHkg6ItbNW2jyyV7rhTUuEtbNo";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);